import { createClient } from '@/lib/supabase/server'
import ReportViewer from '@/components/features/ReportViewer'
import { notFound } from 'next/navigation'
import { getPublicReportBySlug } from '@/lib/reports/share'
import Link from 'next/link'
import { ArrowLeft, Sparkles } from 'lucide-react'

export const metadata = {
  title: 'Shared Business Report — Thinkior AI',
  robots: { index: true, follow: true },
}

export default async function SharedReportPage({
  params,
}: {
  params: { slug: string }
}) {
  const report = await getPublicReportBySlug(params.slug)
  if (!report) return notFound()

  return (
    <div className="min-h-screen">
      {/* Minimal public header */}
      <header className="border-b border-line bg-bg">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between gap-3 flex-wrap">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-fg hover:text-accent transition-colors"
          >
            <Sparkles className="w-4 h-4 text-accent" />
            <span className="font-display font-bold text-[15px]">Thinkior</span>
          </Link>
          <div className="flex items-center gap-3">
            <p className="text-[12px] text-fg-muted font-mono uppercase tracking-caps">
              Shared report · public read-only
            </p>
            <Link
              href="/signup"
              className="inline-flex items-center gap-1.5 bg-accent text-bg hover:bg-accent-hover text-[12.5px] font-semibold px-3 py-1.5 rounded-md transition-colors"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              Build your own
            </Link>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-8">
        <ReportViewer
          report={
            report.report_data && typeof report.report_data === 'object'
              ? (report.report_data as Record<string, unknown>)
              : {}
          }
        />

        <footer className="mt-12 text-center">
          <p className="text-[11px] text-fg-faint font-mono">
            Generated by <span className="text-accent">Thinkior AI</span> · This
            report was shared by its owner. Content reflects analysis at the time of
            generation.
          </p>
        </footer>
      </main>
    </div>
  )
}
